server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root            # 数据库用户名
    password: 123             # 数据库密码
    hikari:
      maximum-pool-size: 10   # 连接池最大连接数
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis:
  type-aliases-package: com.example.userservice.model  # 实体类路径
  mapper-locations: classpath:mapper/*.xml  # 映射文件路径
  configuration:
    map-underscore-to-camel-case: true                  # 驼峰命名法与数据库字段匹配
    cache-enabled: false                                # 缓存是否启用（默认开启，如果需要关闭可以设置为 false）
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
jwt:
  secret: your_jwt_secret_key        # JWT密钥
  expiration: 3600                   # JWT过期时间（秒）
  header: Authorization              # 请求头中携带JWT的字段名称
  prefix: Bearer                    # JWT前缀
